Feature
store-electronics-and-household/store-backend pull request #7
Opened 2023-11-17 04:07 UTC by AleksandrIsa4

Создана схема базы данных
Созданы сущности для БД
Созданы GitHub Actions для проверки при любом pull request и заливки на сервер при закрытии pull request в ветку main
Создана логика создания, изменения, удаления, получения User

2023-11-19 22:36 UTC, nkorzh requested changes

2023-11-19 22:36 UTC, nkorzh commented on src/main/resources/schema.sql
> +    sum_income            VARCHAR(1000) NOT NULL,
цена дохода?
количество дохода?
сумма дохода?

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/model/dto/UserResponce.java
> +public class UserResponce {
Respon**s**e

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/model/dto/UserResponce.java
> +package ru.acceleration.store.model.dto;
пакет dto самостоятельный, почему он лежит внутри model?

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/mapper/UserMapper.java
> +    public static UserResponce toUserResponce(User user) {
рекомендуется использовать mapStruct – он все кодогенерит сам
меньше будет ошибок и меньше времени потратите

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/controller/UserController.java
> +                .collect(Collectors.toList());
нит: кажется можно просто .toList()

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/controller/UserController.java
> +    public UserResponce getUserName(@PathVariable Long id) {
аргумент это id, а в uri `username`. Я не уверен что это работает, а если работает то я бы так не делал

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/controller/UserController.java
> +    public void putUserName(@PathVariable Long id, @RequestBody @Valid UserRequest dto) {
аналогично

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/controller/UserController.java
> +    public void putUserName(@PathVariable Long id, @RequestBody @Valid UserRequest dto) {
UserRequest -> AddUsernameRequestDto ?

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/model/Category.java
> +    private List<Product> products;
по одной категории может быть очень много продуктов
мы точно так хотим делать?

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/model/Outcome.java
> +//    @JoinColumn(name = "order_id")
давайте не мержить закомментированный код в мастер?

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/model/Outcome.java
> +    @JoinColumn(name = "product_id")
nit: в других моделях поля разделены пустыми строками
рекомендуется делать везде одинаково

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/model/Product.java
> +//    private List<Image> images;
закомменченный код

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/service/UserService.java
> +    public User getUserName(Long id) {
может getById ?
причем тут username не ясно

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/service/UserService.java
> +        userRepository.delete(user);
достаточно просто delete и провермть что updated row_count == 1

2023-11-19 22:36 UTC, nkorzh commented on src/main/java/ru/acceleration/store/service/UserService.java
> +    public void putUserName(Long id, User user) {
createUser / addUser?
зачем получаем id?
при сохранении в бд должен unique constraint сработать

find не нужен опять

2023-11-19 22:36 UTC, nkorzh commented on src/test/java/ru/acceleration/store/StoreApplicationTests.java
> +    @Test
тестиков бы на контроллер...(

2023-11-20 11:08 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS attributes
Исправил.

2023-11-20 11:14 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +    CONSTRAINT products_attributes_id PRIMARY KEY (attribute_id)
Исправил нейминг.

2023-11-20 11:15 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +    attribute_type_id BIGINT NOT NULL REFERENCES attribute_type(attribute_type_id) ON DELETE CASCADE,
Эту логику мы реализуем в сервисе.

2023-11-20 11:29 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS sales
Да, исправил.

2023-11-20 11:31 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +    size_sales           VARCHAR(100) NOT NULL,
Исправил.

2023-11-20 11:32 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +    size_sales           VARCHAR(100) NOT NULL,
Исправил на capacity.

2023-11-20 11:43 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +    sum_income            VARCHAR(1000) NOT NULL,
исправил нейминг.

2023-11-20 11:43 UTC, IvanMartynovLETI commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS images_array
Таблица исправлена.

2023-11-21 14:07 UTC, merged